name: 2024-domhain_RNASeq
channels:
  - defaults
  - bioconda
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - bioconda::multiqc=1.19
  - bioconda::fastqc=0.12.1
  - bioconda::cutadapt=4.6
  - bioconda::trinity=2.1.1-6




  - bioconda::seqtk=1.3
  - bioconda::star=2.7.5c
    - bioconda::subread=2.0.1
      - conda-forge::parallel=20220222