#PBS -N bwt_index
#PBS -l select=1:ncpus=1:mem=20gb
#PBS -l walltime=72:00:00
#PBS -j oe
#PBS -m abe

# move to folder with data
cd /scratch1/amann3/domhain_RNASeq-1.17.24/rRNA_map

# load modules
module add bowtie2/2.5.2

# run
bowtie2-build silva_rRNA.fa silva_rRNA.db

# do same for human genome
cd /scratch1/amann3/domhain_RNASeq-1.17.24/human_map
bowtie2-build GRCh38.p14.genome.fa GRCh38.p14.genome.db
