#PBS -N remove_human_rRNA
#PBS -l select=1:ncpus=1:mem=750gb
#PBS -l walltime=72:00:00
#PBS -j oe
#PBS -m abe
#PBS -q bigmem

# load modules
module add python/3.9.7

# concatenate filtered ids for each sample
cd /scratch/amann3/human_map
ls *ids | sed 's/.sam.ids//' | while read line; do cat $line.sam.ids /scratch/amann3/rRNA_map/$line.sam.ids | sort | uniq > /scratch/amann3/filtered/$line.filt.ids; done

echo 'Reads to be filtered concatenated'

# now remove unwanted reads
cd /scratch/amann3/filtered
ls *ids | sed 's/.filt.ids//' | while read line; do python /scratch/amann3/remove_seqs.py -f /scratch/amann3/merged_Qfiltered/$line.1.fastq.gz -i $line.filt.ids -o $line.1.fastq; done
ls *ids | sed 's/.filt.ids//' | while read line; do python /scratch/amann3/remove_seqs.py -f /scratch/amann3/merged_Qfiltered/$line.2.fastq.gz -i $line.filt.ids -o $line.2.fastq; done

echo 'Filtering complete'
